"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { useWallet } from "@/components/wallet-provider"

export default function ReferralStats() {
  const { isConnected } = useWallet()

  // Mock data - would be fetched from an API in a real implementation
  const referralStats = {
    totalReferrals: 12,
    activeReferrals: 8,
    pendingReferrals: 4,
    totalEarned: "600 BEX",
    nextTier: {
      current: 12,
      required: 25,
      reward: "10% → 15%",
    },
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Your Referral Stats</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {isConnected ? (
          <>
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 border rounded-md">
                <p className="text-sm text-muted-foreground">Total Referrals</p>
                <p className="text-2xl font-bold">{referralStats.totalReferrals}</p>
              </div>
              <div className="p-4 border rounded-md">
                <p className="text-sm text-muted-foreground">Total Earned</p>
                <p className="text-2xl font-bold text-emerald-500">{referralStats.totalEarned}</p>
              </div>
              <div className="p-4 border rounded-md">
                <p className="text-sm text-muted-foreground">Active Referrals</p>
                <p className="text-2xl font-bold">{referralStats.activeReferrals}</p>
              </div>
              <div className="p-4 border rounded-md">
                <p className="text-sm text-muted-foreground">Pending Referrals</p>
                <p className="text-2xl font-bold">{referralStats.pendingReferrals}</p>
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <p className="text-sm">Next Tier Progress</p>
                <p className="text-sm font-medium">
                  {referralStats.nextTier.current}/{referralStats.nextTier.required} Referrals
                </p>
              </div>
              <Progress
                value={(referralStats.nextTier.current / referralStats.nextTier.required) * 100}
                className="h-2"
              />
              <p className="text-xs text-muted-foreground">
                Reach {referralStats.nextTier.required} referrals to increase your reward from{" "}
                {referralStats.nextTier.reward}
              </p>
            </div>

            <div className="p-4 border rounded-md">
              <p className="text-sm text-muted-foreground">Current Reward Rate</p>
              <p className="text-xl font-bold">10% of referred users' fees</p>
              <p className="mt-1 text-xs text-muted-foreground">
                You earn 10% of the platform fees generated by users you refer for their first 3 months
              </p>
            </div>
          </>
        ) : (
          <div className="flex flex-col items-center justify-center p-8 text-center border rounded-md">
            <p className="mb-4 text-muted-foreground">Connect your wallet to see your referral stats</p>
            <Button>Connect Wallet</Button>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// Import Button component to fix the error
import { Button } from "@/components/ui/button"
